services:
  app:
    image: ${IMAGE}
    container_name: myapp
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./firebase-key.json:/app/firebase-key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-key.json
      - TZ=Asia/Seoul
    restart: always

    depends_on:
       - redis

  redis:
     image: redis:7-alpine
     container_name: redis
     ports:
       - "6379:6379"
     command: ["redis-server","--appendonly","yes"]
     restart: always
version: "3.8"


