db.url = jdbc:mysql://localhost:3306/matchumoney?useSSL=false&serverTimezone=Asia/Seoul
db.username = root
db.password =
db.driverClassName = com.mysql.cj.jdbc.Driver

oauth.clientId = ${KAKAO_CLIENT_ID}
oauth.redirectUri = ${KAKAO_REDIRECT_URI}
oauth.tokenUri = https://kauth.kakao.com/oauth/token
oauth.userInfoUri = https://kapi.kakao.com/v2/user/me