db.url = ${DB_URL}
db.username = ${DB_USERNAME}
db.password = ${DB_PASSWORD}
db.driverClassName = com.mysql.cj.jdbc.Driver

oauth.clientId = ${KAKAO_CLIENT_ID}
oauth.redirectUri = ${KAKAO_REDIRECT_URI}
oauth.tokenUri = https://kauth.kakao.com/oauth/token
oauth.userInfoUri = https://kapi.kakao.com/v2/user/me

jwt.secret=${JWT_SECRET}
jwt.access.expiration=1800000
jwt.refresh.expiration=3600000
jwt.access.header=Authorization

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

mydata.clientId=${CLIENT_ID}
mydata.clientSecret=${CLIENT_SECRET}
mydata.publicKey=${PUBLIC_KEY}

codef.client-id=0ca3a53d-2d54-4c20-a6b7-5caf2947f13c
codef.client-secret=81d4e877-adec-4a77-b0bf-2044628f96d7
codef.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkch+FbXJugv1jGfHwX/NX08RTcKr+87igfcyoro2HGC4rN3nIFCb8Jx80FquTWbb4uPRCKeQYddOS8a2L6hZmcFl5Yyg2rWVPJkWF3GT3FrK2qhVANueA83DySQoiCnwu5ejjIvlOv5Z081JbleuNYDCq6fFrKJiE5pKtGFGDKiB4MhT3twuxp8xZlZgk9e+FrSTg6tsBZuqGByRrnAQNxXptSXjVypq4PxMdX6d8sfiPNoPsgEX9CmXalCWt+s0MQMsnARPcJGKYA4CKDs5uMw/BrLqPPI2Ng0UhZCCvsinF8ogUgD0CdvqaMFeip5hSYYVn8/1f2GglD4j+gpkJQIDAQAB

openai.api.key=${OPENAI_API_KEY}

# 100? ???
#codef.client-id=b0454c9d-2e8c-462f-9ba2-996529ac5304
#codef.client-secret=90747cd8-a342-42c6-9379-de511f9ea81f
#codef.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmNxxjk4vYkk+XlilHJiBihixLF0MoFDV/99PKPfbejU3nAaZRFXHhkBIs+Jb8doX8VxvTPcV/R6fRJt7EWHwUXrKsWT2tX8a4zZxdyz8yygdSyvRC6LSmvRUHoWClUq6Gn3PpjSCw35An4yu9YyJX/6g/4WpFkX6SVAvwEkVaEbXmFMrRHK+W4F3mZyZDAEt+VZZu15/lVziWJV9Cr2TT1WbG4rNs8GSgQipnhFu6YETEn/LhrzT9OYjtfh5+6eRxbcplno8U6Lfb/DgRhTh+zxacZFfwi8eKEAF3dJEscaWtZSG5bMWG+scz9apOW9yaibqSaVUrWqIN/7hpxfkOQIDAQAB
