db.url = ${DB_URL}
db.username = ${DB_USERNAME}
db.password = ${DB_PASSWORD}
db.driverClassName = com.mysql.cj.jdbc.Driver

oauth.clientId = ${KAKAO_CLIENT_ID}
oauth.redirectUri = ${KAKAO_REDIRECT_URI}
oauth.tokenUri = https://kauth.kakao.com/oauth/token
oauth.userInfoUri = https://kapi.kakao.com/v2/user/me

jwt.secret=${JWT_SECRET}
jwt.access.expiration=3000000000000000
jwt.refresh.expiration=3600000
jwt.access.header=Authorization

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

mydata.clientId=${CLIENT_ID}
mydata.clientSecret=${CLIENT_SECRET}
mydata.publicKey=${PUBLIC_KEY}
